### ISSUE TITLE
Does not use startup communication cost vector?

### ISSUE THREAD

**Issue by lfdversluis** [mackncheesiest/heft#14]
In the paper by Topcuoglu et al. a startup communication vector L is used. Glancing at the code, I don't see it being defined?

**Comment by mackncheesiest** [comment]
Actually, you're right! We don't have the startup communication cost defined in the code.

In our applications it hasn't been necessary but we can certainly add it as another parameter, probably with a default value of all zeroes.

**Comment by mackncheesiest** [comment]
Does #15 resolve the issue sufficiently? I only have a pytest included for a startup communication vector of 0's as I don't have the time to follow through on a hand calculation of how the canonical schedule is affected with, say `[1, 2, 3]`.

**Comment by lfdversluis** [comment]
Sorry for the late response. Yes, that looks good. Keep in mind that if you now run the script without any arguments, you still do not (fully) run the example in Topcuoglu et al. paper. I am not sure if people need this, but just a FYI :)

**Comment by mackncheesiest** [comment]
Just curious, but in what way? To the best of my ability to discern the time axis, the output schedule generated matches the chart in Fig. 4(a) for each individual task, and overall graph's makespan is 80. 

I was never able to find the definition of the communication cost matrix or startup cost vector documented in the paper for this particular example, but a communication matrix of
```
[0, 1, 1,
 1, 0, 1,
 1, 1, 0]
```
coupled with a startup cost vector of `[0, 0, 0]` would seem to recreate that chart exactly given the constraints of the PE computation costs and DAG edge weighting.

**Comment by lfdversluis** [comment]
Hmm weird, tasks are initially ranked using the average startup cost, so this shouldn't make a difference as it would be the same for all tasks. However, when computing the estimated finish time, the communication startup cost of the processor that sends the data (let's call it p1) to another processor (px where x != 1) should be included according to the paper.

**Comment by mackncheesiest** [comment]
I suppose even more notably, the rank_u we compute for each node in the graph is identical with the one presented in Table I as evidenced by 
[this regression test](https://github.com/mackncheesiest/heft/blob/644d3b56ea16feafac498b60fd4c2f6adebd95ff/heft/test/test_heft.py#L179-L215) as well as the output presented when the algorithm is run with DEBUG logging enabled (and rank u values are printed), which means that the average communication startup cost is 0 in the example they're using.

**Comment by lfdversluis** [comment]
Sounds like we found out what is happening in the paper then. Weird that they do not mention this. I think we can close this issue as the code has been added. 👍
